services:
  postgres-db:
    image: postgres:16.2-alpine3.19
    container_name: postgres-db
    restart: always
    user: postgres
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - net_backend

  spring_app_api:
    build:
      context: .
    image: spring_app_api-image
    container_name: spring_app_api
    ports:
      - 5000:5000
    depends_on:
      postgres-db:
        condition: service_healthy
    networks:
      - net_backend

volumes:
   db-data:
networks:
  net_backend:
    driver: bridge


