server:
  port: 5000

spring:
  datasource:
    url: jdbc:postgresql://host.docker.internal:5434/your_db
    username: your_user
    password: yourpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
#  sql:
#    init:
#      data-locations: classpath:data/tbl_products.sql
#      mode: always



